[package]
name = "bridge-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
argh = "0.1.9"
hex = "0.4.3"
melodeon = "0.5.15"
melorun = "0.7.10"
mil = "0.4.1"
serde_yaml = "0.9.14"
themelio-stf = "0.11.12"
themelio-structs = "0.2.0"
tokio = { version = "1", features = ["full"] }